name: Terraform Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    uses: syltek/gh-workflows/.github/workflows/terraform_modules.yaml@main
    secrets: inherit
